const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const {EventEmitter}=require('node:events');const {ObjectId}=require('mongodb');
function compile(path,dependencies={}){const context={exports:{},require:name=>dependencies[name]||require(name),Request,Response,File,FormData,Buffer,console,URL,Date};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return context.exports}
const model=compile('src/lib/creators.ts');
const NextResponse=class extends Response{static json(body,init){return new this(JSON.stringify(body),{...init,headers:{'Content-Type':'application/json',...init?.headers}})}};
function matches(row,query){return Object.entries(query).every(([key,value])=>value&&typeof value==='object'&&!(value instanceof ObjectId)?('$in'in value?value.$in.includes(row[key]):'$gt'in value?row[key]>value.$gt:false):String(row[key])===String(value))}
function database(){const records={};return {records,collection(name){const rows=records[name]??=[];return {async insertOne(row){rows.push(row);return{insertedId:row.id}},async findOne(query){const row=rows.find(row=>matches(row,query));return row?{...row}:null},async countDocuments(query){return rows.filter(row=>matches(row,query)).length},async findOneAndUpdate(query,update){let row=rows.find(row=>matches(row,query));if(!row){row={...query};rows.push(row)}Object.assign(row,update.$set);for(const[key,value]of Object.entries(update.$inc||{}))row[key]=(row[key]||0)+value;return row},async updateOne(query,update,options){let row=rows.find(row=>matches(row,query));if(!row&&options?.upsert){row={...query};rows.push(row)}if(row)Object.assign(row,update.$set);return{matchedCount:row?1:0}},find(query){const found=rows.filter(row=>matches(row,query));return {sort(){return this},limit(){return this},async toArray(){return found}}}}}}}
test('application -> approval -> selection -> hidden, with private files and finance isolated',async()=>{
 const db=database();const files=new Map();let staff=false,finance=false;
 class GridFSBucket{constructor(db,options){this.prefix=options.bucketName+':'}openUploadStream(name,options){const stream=new EventEmitter();stream.id=new ObjectId();stream.end=buffer=>{files.set(this.prefix+String(stream.id),{_id:stream.id,metadata:options.metadata,buffer});stream.emit('finish')};return stream}async delete(id){files.delete(this.prefix+String(id))}find(query){const prefix=this.prefix;return {async next(){return files.get(prefix+String(query._id))}}}openDownloadStream(id){const prefix=this.prefix;return (async function*(){yield files.get(prefix+String(id)).buffer})()}}
 const auth={requireAdmin:async()=>staff?null:NextResponse.json({error:'Unauthorized'},{status:401}),getAdminSession:async()=>staff?{email:'staff@example.test'}:null,canManageCreatorFinance:async()=>staff&&finance,sameOrigin:()=>true};
 const dependencies={'next/server':{NextResponse},'@/lib/mongodb':{default:Promise.resolve({db:()=>db})},'@/lib/creators':model,'@/lib/auth':auth,mongodb:{ObjectId,GridFSBucket}};
 const apply=compile('src/app/api/creators/apply/route.ts',dependencies),admin=compile('src/app/api/creators/admin/route.ts',dependencies),media=compile('src/app/api/creators/media/[id]/route.ts',dependencies),financial=compile('src/app/api/creators/finance/route.ts',dependencies),selections=compile('src/app/api/creators/selections/route.ts',dependencies);
 const identity=compile('src/app/api/creators/identity/route.ts',dependencies);
 const json=(body,method='POST')=>new Request('http://localhost:3001/test',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const payload={author:'Test Creator',fullName:'Private Full Name',nickname:'Nickname',birthday:'2000-01-01',province:'Bangkok',phone:'0000000000',email:'creator@example.test',categories:['Beauty'],socials:[{platform:'TikTok',url:'https://example.test/creator',followers:'120K'}],portfolio:['https://example.test/work'],rates:{post:'5000'},terms:true,privacy:true,bank:'Private bank',accountName:'Private account name',accountNumber:'private-account',taxId:'private-tax',billingAddress:'Private billing address'};
 const form=()=>{const f=new FormData();f.set('data',JSON.stringify(payload));f.set('photo',new File([Buffer.from('mock image')],'photo.png',{type:'image/png'}));f.set('idCard',new File([Buffer.from([137,80,78,71,13,10,26,10,0])],'identity.png',{type:'image/png'}));f.set('mediaKit',new File([Buffer.from('%PDF-mock')],'kit.pdf',{type:'application/pdf'}));return f};
 const response=await apply.POST(new Request('http://localhost:3001/api/creators/apply',{method:'POST',body:form()}));assert.equal(response.status,201);assert.equal(db.records.creators.length,1);
 const creator=db.records.creators[0];assert.equal(db.records.creator_finance[0].accountNumber,'private-account');assert.equal(db.records.creator_finance[0].taxId,'private-tax');const submittedIdCard=db.records.creator_finance[0].idCardFileId;assert.equal((await media.GET(new Request('http://localhost:3001/file'),{params:Promise.resolve({id:submittedIdCard})})).status,404);assert.equal(creator.status,'pending');assert.equal(creator.accountNumber,undefined);assert.equal(creator.taxId,undefined);assert.equal(creator.consent.privacy,true);
 const fileRequest=id=>media.GET(new Request('http://localhost:3001/file'),{params:Promise.resolve({id})});
 assert.equal((await fileRequest(creator.photoId)).status,404);assert.equal((await fileRequest(creator.mediaKitId)).status,404);
 assert.equal((await selections.POST(json({name:'Client',email:'client@example.test',creatorIds:[creator.id]}))).status,409);
 assert.equal((await admin.PATCH(json({id:creator.id,status:'approved'},'PATCH'))).status,401);
 staff=true;finance=true;
 assert.equal((await financial.PUT(json({creatorId:creator.id,accountNumber:'123'},'PUT'))).status,200);
 assert.equal((await fileRequest(creator.mediaKitId)).status,200);
 assert.equal((await admin.PATCH(json({id:creator.id,status:'approved'},'PATCH'))).status,200);
 assert.equal((await financial.PUT(json({creatorId:creator.id,accountNumber:'123',taxId:'private-tax'},'PUT'))).status,200);
 assert.equal(db.records.creator_finance[0].accountNumber,'123');assert.equal(creator.accountNumber,undefined);
 const identityForm=new FormData();identityForm.set('creatorId',creator.id);identityForm.set('file',new File([Buffer.from([137,80,78,71,13,10,26,10,0])],'id.png',{type:'image/png'}));
 const upload=await identity.POST(new Request('http://localhost:3001/identity',{method:'POST',body:identityForm}));assert.equal(upload.status,200);const document=(await upload.json()).idCardFileId;
 assert.equal((await fileRequest(document)).status,404,'identity document must not be served by generic media route, even to staff');
 const identityRequest=()=>identity.GET(new Request(`http://localhost:3001/identity?creatorId=${creator.id}`));assert.equal((await identityRequest()).status,200);
 finance=false;assert.equal((await identityRequest()).status,403);staff=false;assert.equal((await identityRequest()).status,403);staff=true;

 finance=false;assert.equal((await financial.GET(new Request(`http://localhost:3001/finance?id=${creator.id}`))).status,403);
 const publicData=JSON.stringify(model.publicCreator(creator));assert.equal(publicData.includes(payload.fullName),false);assert.equal(publicData.includes(payload.email),false);assert.equal(publicData.includes('private-tax'),false);
 staff=false;assert.equal((await fileRequest(creator.photoId)).status,200);assert.equal((await fileRequest(creator.mediaKitId)).status,404);
 assert.equal((await selections.POST(json({name:'Client',email:'client@example.test',creatorIds:[creator.id]}))).status,201);assert.equal(db.records.creator_selections[0].creators[0].author,'Test Creator');
 assert.equal((await selections.GET()).status,401);
 staff=true;assert.equal((await admin.PATCH(json({id:creator.id,status:'hidden'},'PATCH'))).status,200);staff=false;assert.equal((await fileRequest(creator.photoId)).status,404);assert.equal((await selections.POST(json({name:'Client',email:'client@example.test',creatorIds:[creator.id]}))).status,409);
});
