/* eslint-disable @typescript-eslint/no-require-imports -- CommonJS fixtures for Node tests. */
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function compile(file,deps={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>deps[name]||require(name),console,Date,URL,Request,Response});return exports}
function read(object,key){return key.split('.').reduce((value,part)=>Array.isArray(value)?value.map(item=>item?.[part]):value?.[part],object)}
function evaluate(value,document,variables={}){
 if(typeof value==='string'&&value.startsWith('$$'))return read(variables,value.slice(2));if(typeof value==='string'&&value.startsWith('$'))return read(document,value.slice(1));if(value===null||typeof value!=='object'||value instanceof Date)return value;if(Array.isArray(value))return value.map(item=>evaluate(item,document,variables));
 const ev=input=>evaluate(input,document,variables);if('$literal'in value)return value.$literal;if('$ifNull'in value){const [a,b]=value.$ifNull;return ev(a)??ev(b)}if('$size'in value)return ev(value.$size).length;if('$concatArrays'in value)return ev(value.$concatArrays).flat();if('$eq'in value){const [a,b]=ev(value.$eq);return a===b}if('$ne'in value){const [a,b]=ev(value.$ne);return a!==b}if('$lt'in value){const [a,b]=ev(value.$lt);return a<b}if('$in'in value){const [a,b]=ev(value.$in);return b.includes(a)}if('$and'in value)return ev(value.$and).every(Boolean);if('$not'in value)return !ev(value.$not)[0];if('$cond'in value){const [a,b,c]=value.$cond;return ev(ev(a)?b:c)}if('$slice'in value){const [a,b]=ev(value.$slice);return b<0?a.slice(b):a.slice(0,b)}if('$filter'in value){const {input,as,cond}=value.$filter;return ev(input).filter(item=>evaluate(cond,document,{...variables,[as]:item}))}if('$map'in value){const {input,as,in:expression}=value.$map;return ev(input).map(item=>evaluate(expression,document,{...variables,[as]:item}))}return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,ev(item)]))
}
function matches(document,query){return Object.entries(query).every(([key,value])=>{if(key==='$expr')return evaluate(value,document);const actual=read(document,key);if(value&&typeof value==='object')return '$exists'in value?(actual!==undefined)===value.$exists:'$ne'in value?actual!==value.$ne:'$in'in value?value.$in.includes(actual):false;return Array.isArray(actual)?actual.includes(value):actual===value})}
const next={NextResponse:{json:(body,options={})=>new Response(JSON.stringify(body),{status:options.status||200,headers:{'Content-Type':'application/json',...options.headers}})}};
test('private work history counts deliveries and received products, updates atomically and enforces blacklist until manual republication',async()=>{
 let staff=true;
 const record={id:'creator-1',author:'Creator',status:'approved',categories:['Beauty'],socials:[{platform:'TikTok',url:'https://example.test'}],photoId:'photo-1'};
 const collection={findOne:async query=>matches(record,query)?structuredClone(record):null,updateOne:async(query,update)=>{if(!matches(record,query))return {matchedCount:0};if(Array.isArray(update)){for(const stage of update)Object.assign(record,evaluate(stage.$set,record))}else{Object.assign(record,update.$set);for(const key of Object.keys(update.$unset||{}))delete record[key]}return {matchedCount:1}}};
 const auth={getAdminSession:async()=>staff?{email:'staff@example.test'}:null,requireAdmin:async()=>staff?null:next.NextResponse.json({error:'Unauthorized'},{status:401}),sameOrigin:req=>!req.headers.get('origin')||req.headers.get('origin')==='http://localhost:3001'};
 const model=compile('src/lib/creators.ts'),workModel=compile('src/lib/creator-work.ts');const deps={'next/server':next,'@/lib/mongodb':{default:Promise.resolve({db:()=>({collection:()=>collection})})},'@/lib/auth':auth,'@/lib/creators':model,'@/lib/creator-work':workModel};
 const api=compile('src/app/api/creators/work/route.ts',deps),admin=compile('src/app/api/creators/admin/route.ts',deps);
 const request=(body,origin)=>new Request('http://localhost:3001/api/creators/work',{method:'PUT',headers:{'Content-Type':'application/json',...(origin?{origin}:{})},body:JSON.stringify(body)});
 const work={campaign:'Campaign',brand:'Brand',acceptedDate:'2026-10-01',dueDate:'2026-10-07',productReceived:true,receivedDate:'2026-10-02',status:'accepted',notes:'',evidenceUrl:''};
 let response=await api.PUT(request({creatorId:record.id,action:'saveWork',work}));assert.equal(response.status,200);let detail=await response.json();assert.deepEqual(detail.stats,{total:1,delivered:0,missed:0,productOutstanding:1});assert.equal(detail.records[0].createdBy,'staff@example.test');assert.equal(workModel.isWorkOverdue(detail.records[0],'2026-10-08'),true);
 response=await api.PUT(request({creatorId:record.id,action:'saveWork',work:{...work,id:detail.records[0].id,status:'missed'}}));assert.equal(response.status,400);
 response=await api.PUT(request({creatorId:record.id,action:'saveWork',work:{...work,id:detail.records[0].id,status:'missed',notes:'Confirmed after follow-up'}}));detail=await response.json();assert.deepEqual(detail.stats,{total:1,delivered:0,missed:1,productOutstanding:1});assert.equal(detail.records.length,1);
 response=await api.PUT(request({creatorId:record.id,action:'saveWork',work:{...work,campaign:'$literal-is-not-executed',productReceived:false,status:'delivered'}}));detail=await response.json();assert.equal(detail.records[1].campaign,'$literal-is-not-executed');assert.deepEqual(detail.stats,{total:2,delivered:1,missed:1,productOutstanding:1});
 response=await api.PUT(request({creatorId:record.id,action:'blacklist',active:true,reason:''}));assert.equal(response.status,400);
 response=await api.PUT(request({creatorId:record.id,action:'blacklist',active:true,reason:'Confirmed failed campaign'}));detail=await response.json();assert.equal(detail.profileStatus,'hidden');assert.equal(record.blacklist.active,true);assert.equal(record.blacklistLog.length,1);
 const approvedRequest=()=>new Request('http://localhost:3001/api/creators/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:record.id,status:'approved'})});assert.equal((await admin.PATCH(approvedRequest())).status,409);
 response=await api.PUT(request({creatorId:record.id,action:'blacklist',active:false,reason:'Resolved with creator'}));assert.equal(response.status,200);assert.equal(record.status,'hidden');assert.equal(record.blacklist.active,false);assert.equal((await admin.PATCH(approvedRequest())).status,200);
 const publicData=model.publicCreator(record);for(const key of ['workRecords','workStats','blacklist','blacklistLog'])assert.equal(Object.hasOwn(publicData,key),false);
 const privateResponse=await api.GET(new Request('http://localhost:3001/api/creators/work?id=creator-1'));assert.equal(privateResponse.headers.get('cache-control'),'no-store');assert.equal(Object.hasOwn(await privateResponse.json(),'contact'),false);
 assert.equal((await api.PUT(request({creatorId:record.id,action:'blacklist',active:true,reason:'Test'},'https://other.test'))).status,403);
 staff=false;assert.equal((await api.GET(new Request('http://localhost:3001/api/creators/work?id=creator-1'))).status,401);assert.equal((await api.PUT(request({creatorId:record.id,action:'saveWork',work}))).status,401);
});
