const test=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const vm=require('node:vm');
test('six-step application retains profile data, validates required sections, requires private financial details and identity attachment while excluding them from the local draft',async()=>{
 const states=[];let cursor=0;const storage=new Map();const React={useRef:()=>({current:null}),useState:initial=>{const index=cursor++;if(!(index in states))states[index]=initial;return[states[index],value=>{states[index]=typeof value==='function'?value(states[index]):value}]}};
 const noop=()=>null;const dependencies={react:React,'next/image':{default:noop},'@/navigation':{Link:noop},'@/components/layout/Navbar':{Navbar:noop},'@/components/layout/Footer':{Footer:noop},'lucide-react':new Proxy({},{get:()=>noop}),'./Application.module.css':{default:{}}};
 const context={exports:{},require:name=>dependencies[name]||require(name),URL,File,FormData,sessionStorage:{setItem:(key,value)=>storage.set(key,value),getItem:key=>storage.get(key)||null,removeItem:key=>storage.delete(key)},document:{getElementById:()=>({scrollIntoView(){}})},window:{matchMedia:()=>({matches:false})},fetch:()=>{throw Error('No actual submissions during UI tests')}};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/app/[locale]/influencers/apply/ApplicationForm.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,context);
 const props={categories:['Beauty','Food'],genders:['หญิง','ชาย'],terms:'Terms',privacy:'Privacy'};const render=()=>{cursor=0;return context.exports.default(props)};
 const flatten=element=>{if(!element)return[];if(Array.isArray(element))return element.flatMap(flatten);if(typeof element!=='object')return[element];return[element,...flatten(element.props?.children)]};const find=(type,predicate)=>flatten(render()).find(node=>node?.type===type&&predicate(node.props));const text=()=>flatten(render()).filter(node=>typeof node==='string').join(' ');const set=(name,value)=>find('input',p=>p.name===name).props.onChange({target:{value}});const next=()=>find('form',()=>true).props.onSubmit({preventDefault(){}});
 for(const name of ['firstName','lastName','nickname','author','birthday','province','phone','email'])set(name,name==='email'?'ui@example.test':name==='birthday'?'2000-01-01':`Test ${name}`);
 await next();assert.match(text(),/กรุณาอัปโหลดรูปโปรไฟล์/);
 const photo=new File(['mock'],'profile.png',{type:'image/png'});find('input',p=>p.name==='photo').props.onChange({target:{files:[photo]}});await next();assert.equal(states[0],1);
 await next();assert.match(text(),/กรุณากรอกโซเชียล/);set('TikTok-url','https://example.test/creator');await next();assert.equal(states[0],2);
 await next();assert.match(text(),/กรุณาเลือกประเภทคอนเทนต์/);const label=find('label',p=>Array.isArray(p.children)&&p.children.includes('Beauty'));label.props.children[0].props.onChange();await next();assert.equal(states[0],3);
 set('rate-post','5000');await next();assert.equal(states[0],4);assert.match(text(),/ข้อมูลบัญชีธนาคาร/);await next();assert.equal(states[0],4);assert.match(text(),/กรุณากรอกข้อมูลบัญชี/);for(const name of ['bank','accountName','accountNumber','taxId'])set(name,'Private '+name);find('textarea',p=>p.name==='billingAddress').props.onChange({target:{value:'Private address'}});find('input',p=>p.name==='idCard').props.onChange({target:{files:[new File(['mock'],'identity.png',{type:'image/png'})]}});
 await next();assert.equal(states[0],5);assert.match(text(),/Test author/);assert.match(text(),/TikTok/);assert.match(text(),/Terms/);assert.match(text(),/Privacy/);
 find('button',p=>p.onClick&&flatten(p.children).includes('บันทึกแบบร่าง')).props.onClick();const saved=JSON.parse(storage.get('shiya-application-draft'));assert.equal(saved.values['rate-post'],'5000');assert.equal(saved.selected[0],'Beauty');assert.equal(Object.hasOwn(saved,'photo'),false);for(const key of ['bank','accountName','accountNumber','taxId','billingAddress'])assert.equal(Object.hasOwn(saved.values,key),false,key);assert.equal(Object.hasOwn(saved,'idCard'),false);
 find('button',p=>flatten(p.children).includes('ย้อนกลับ')).props.onClick();assert.equal(states[0],4);
});
