 'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import CreatorAdminNav from '@/components/admin/CreatorAdminNav';
import {defaultCategories,defaultGenders} from '@/lib/creators';
import styles from '@/components/admin/CreatorPages.module.css';
const input='mt-2 block w-full rounded-lg border border-slate-300 bg-white p-3 text-sm text-slate-900';
const button='rounded-lg bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50';
export default function CreatorSettings(){
const [categories,setCategories]=useState(defaultCategories),[genders,setGenders]=useState(defaultGenders),[terms,setTerms]=useState(''),[privacy,setPrivacy]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(false),[retry,setRetry]=useState(0);
useEffect(()=>{const controller=new AbortController();fetch('/api/influencer',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{setCategories(data.profileCategories||defaultCategories);setGenders(data.profileGenders||defaultGenders);setTerms(data.applicantTerms||'');setPrivacy(data.applicantPrivacy||'');setLoaded(true)}).catch(()=>{if(!controller.signal.aborted)setError(true)});return ()=>controller.abort()},[retry]);
const configure=async()=>{setBusy(true);try{const clean=(values:string[])=>[...new Set(values.map(v=>v.trim()).filter(Boolean))];const nextCategories=clean(categories),nextGenders=clean(genders);const response=await fetch('/api/influencer',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileCategories:nextCategories,profileGenders:nextGenders,applicantTerms:terms,applicantPrivacy:privacy})});if(!response.ok)throw Error();setCategories(nextCategories);setGenders(nextGenders);toast.success('บันทึกการตั้งค่าแล้ว')}catch{toast.error('บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
return <div className={`admin-page ${styles.page}`}><header className={styles.header}><div><h1>หมวดหมู่ / ข้อตกลง</h1><p>จัดการตัวเลือกที่ใช้ในฟอร์มสมัครและ Catalog พร้อมข้อความข้อตกลง</p></div><button disabled={!loaded||busy} className={button} onClick={configure}>{busy?'กำลังบันทึก…':'บันทึกการตั้งค่า'}</button></header><CreatorAdminNav/>{error?<div className={styles.panel}>โหลดไม่สำเร็จ <button onClick={()=>{setError(false);setRetry(v=>v+1)}}>ลองใหม่</button></div>:!loaded?<div className={styles.panel} role="status">กำลังโหลดการตั้งค่า…</div>:<div className={styles.settings}>
<div className="grid gap-5 md:grid-cols-2">{[{title:'หมวดหมู่อินฟลูเอนเซอร์',values:categories,set:setCategories},{title:'ตัวเลือกเพศ',values:genders,set:setGenders}].map(group=><section key={group.title} className="rounded-2xl border bg-white p-5"><h2 className="font-semibold mb-4">{group.title}</h2><div className="space-y-2">{group.values.map((value,index)=><div key={index} className="flex gap-2"><input aria-label={`${group.title} ${index+1}`} value={value} onChange={e=>group.set(previous=>previous.map((v,i)=>i===index?e.target.value:v))} className="min-w-0 flex-1 rounded-lg border p-2"/><button onClick={()=>group.set(previous=>previous.filter((_,i)=>i!==index))} className="text-red-700 text-sm">ลบ</button></div>)}</div><button onClick={()=>group.set(previous=>[...previous,''])} className="mt-3 text-blue-700 text-sm">+ เพิ่มตัวเลือก</button></section>)}</div><section className="rounded-2xl border bg-white p-6 space-y-5"><label className="block text-sm">เงื่อนไขการสมัคร (เว้นว่างใช้ข้อความเริ่มต้น)<textarea value={terms} onChange={e=>setTerms(e.target.value)} rows={5} className={input}/></label><label className="block text-sm">Privacy Notice (เว้นว่างใช้ข้อความเริ่มต้น)<textarea value={privacy} onChange={e=>setPrivacy(e.target.value)} rows={6} className={input}/></label><button disabled={busy} onClick={configure} className={button}>บันทึกการตั้งค่า</button></section></div>}</div>;}
