'use client';
import {useEffect,useRef,useState} from 'react';
import CreatorAdminNav from '@/components/admin/CreatorAdminNav';
import styles from '@/components/admin/CreatorPages.module.css';
type Selection={_id:string;name:string;email:string;phone:string;company:string;message:string;creators:{id:string;author:string}[];createdAt:string};
export default function CreatorSelections(){
const [items,setItems]=useState<Selection[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(false),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[page,setPage]=useState(1),[active,setActive]=useState<Selection|null>(null);const dialog=useRef<HTMLDialogElement>(null);
useEffect(()=>{const controller=new AbortController();fetch('/api/creators/selections',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{setItems(data);setLoaded(true)}).catch(()=>{if(!controller.signal.aborted)setError(true)});return ()=>controller.abort()},[retry]);
useEffect(()=>{if(active)dialog.current?.showModal();else dialog.current?.close()},[active]);
const filtered=items.filter(item=>[item.name,item.company,item.email,item.phone,item.message,...item.creators.map(c=>c.author)].join(' ').toLowerCase().includes(query.trim().toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages),rows=filtered.slice((current-1)*10,current*10);
const exportCsv=()=>{const data=[['วันที่','ลูกค้า','บริษัท','Email','โทร','Influencer','รายละเอียด'],...filtered.map(s=>[s.createdAt,s.name,s.company,s.email,s.phone,s.creators.map(c=>c.author).join(' / '),s.message])];const csv='\uFEFF'+data.map(row=>row.map(value=>'"'+(/^[=+@\-]/.test(value)?"'"+value:value).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='shiya-creator-requests.csv';a.click();URL.revokeObjectURL(url)};
return <div className={`admin-page ${styles.page}`}><header className={styles.header}><div><h1>รายชื่อที่ลูกค้าเลือก</h1><p>ตรวจรายชื่อ Influencer และข้อมูลติดต่อสำหรับประสานงานแคมเปญ</p></div><button disabled={!loaded} onClick={exportCsv}>ส่งออก CSV ({filtered.length})</button></header><CreatorAdminNav/>{error?<div className={styles.panel}>โหลดคำขอไม่สำเร็จ <button onClick={()=>{setError(false);setRetry(v=>v+1)}}>ลองใหม่</button></div>:!loaded?<div className={styles.panel} role="status">กำลังโหลดคำขอ…</div>:<><section className={styles.stats}><article><span>คำขอทั้งหมด</span><strong>{items.length}</strong></article><article><span>ครีเอเตอร์ที่ถูกเลือก (ไม่ซ้ำ)</span><strong>{new Set(items.flatMap(s=>s.creators.map(c=>c.id))).size}</strong></article><article><span>บริษัทที่ติดต่อ</span><strong>{new Set(items.map(s=>s.company.trim()).filter(Boolean)).size}</strong></article></section><div className={styles.panel}><label className={styles.search}>ค้นหาคำขอ<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="ชื่อลูกค้า บริษัท หรือ Influencer"/></label><div className={styles.scroll}><table><thead><tr><th>ลูกค้า / บริษัท</th><th>ช่องทางติดต่อ</th><th>Influencer ที่เลือก</th><th>วันที่ส่งคำขอ</th><th>จัดการ</th></tr></thead><tbody>{rows.map(item=><tr key={item._id}><td><strong>{item.name}</strong><small>{item.company||'ไม่ระบุบริษัท'}</small></td><td>{item.email}<small>{item.phone||'ไม่ระบุเบอร์โทร'}</small></td><td><div className={styles.chips}>{item.creators.slice(0,3).map(c=><span key={c.id}>{c.author}</span>)}{item.creators.length>3&&<span>+{item.creators.length-3}</span>}</div></td><td>{new Date(item.createdAt).toLocaleDateString('th-TH')}</td><td><button onClick={()=>setActive(item)}>ดูรายละเอียด</button></td></tr>)}{!rows.length&&<tr><td colSpan={5} className={styles.empty}>ไม่พบคำขอในรายการนี้</td></tr>}</tbody></table></div><footer className={styles.pagination}><span>{filtered.length} รายการ · หน้า {current} / {pages}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>ก่อนหน้า</button><button disabled={current===pages} onClick={()=>setPage(current+1)}>ถัดไป</button></div></footer></div></>}{active&&<dialog ref={dialog} className={styles.dialog} onCancel={()=>setActive(null)}><header className={styles.header}><div><h2>คำขอจาก {active.name}</h2><p>{active.company||'ไม่ระบุบริษัท'} · {new Date(active.createdAt).toLocaleString('th-TH')}</p></div><button onClick={()=>setActive(null)}>ปิด</button></header><section><h3>ข้อมูลติดต่อ</h3><a href={`mailto:${active.email}`}>{active.email}</a><p>{active.phone||'ไม่ระบุเบอร์โทร'}</p></section><section><h3>Influencer ที่ลูกค้าเลือก ({active.creators.length})</h3><div className={styles.chips}>{active.creators.map(c=><span key={c.id}>{c.author}</span>)}</div></section><section><h3>รายละเอียดแคมเปญ</h3><p className={styles.message}>{active.message||'ไม่ได้ระบุรายละเอียดเพิ่มเติม'}</p></section></dialog>}</div>}
