'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Briefcase,CheckCircle2,AlertTriangle,Package,X,ShieldAlert,ExternalLink,Pencil} from 'lucide-react';
import {toast} from 'sonner';
import {workStatuses,emptyWorkStats,isWorkOverdue,type CreatorWork,type CreatorWorkDetail} from '@/lib/creator-work';
import styles from './CreatorWorkPanel.module.css';
type Draft=Omit<CreatorWork,'createdAt'|'createdBy'|'updatedAt'|'updatedBy'>;
function today(){const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
const emptyDraft=():Draft=>({id:'',campaign:'',brand:'',acceptedDate:today(),dueDate:'',productReceived:false,receivedDate:'',status:'accepted',notes:'',evidenceUrl:''});
export default function CreatorWorkPanel({creatorId,author,onClose,onChange}:{creatorId:string;author:string;onClose:()=>void;onChange:(detail:CreatorWorkDetail)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const editor=useRef<HTMLDivElement>(null);const [data,setData]=useState<CreatorWorkDetail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false),[draft,setDraft]=useState<Draft|null>(null),[reason,setReason]=useState(''),[blacklist,setBlacklist]=useState(false);
 useEffect(()=>{dialog.current?.showModal();const controller=new AbortController();fetch(`/api/creators/work?id=${encodeURIComponent(creatorId)}`,{signal:controller.signal,cache:'no-store'}).then(async response=>{if(!response.ok)throw Error();return response.json()}).then(detail=>{if(controller.signal.aborted)return;setData(detail);setReason(detail.blacklist?.reason||'');setBlacklist(!!detail.blacklist?.active)}).catch(()=>{if(!controller.signal.aborted)setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[creatorId]);
 const draftId=draft?.id;
 useEffect(()=>{if(draftId!==undefined)editor.current?.scrollIntoView({block:'start'})},[draftId]);
 const stats=data?.stats||emptyWorkStats;
 const submit=async(action:'saveWork'|'blacklist')=>{if(busy)return;setBusy(true);try{const response=await fetch('/api/creators/work',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({creatorId,action,...(action==='saveWork'?{work:draft}:{active:blacklist,reason})})});const result=await response.json();if(!response.ok)throw Error(result.error);setData(result);onChange(result);if(action==='saveWork')setDraft(null);toast.success(action==='saveWork'?'บันทึกประวัติรับงานแล้ว':blacklist?'บันทึก Blacklist และซ่อนโปรไฟล์แล้ว':'ยกเลิก Blacklist แล้ว โปรไฟล์ยังซ่อนอยู่จนกว่าจะเผยแพร่ใหม่')}catch(error){toast.error(error instanceof Error?error.message:'บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
 const update=(key:keyof Draft,value:string|boolean)=>setDraft(previous=>previous?{...previous,[key]:value}:previous);
 return <dialog ref={dialog} className={styles.dialog} aria-labelledby="creator-work-heading" onCancel={event=>{if(busy)event.preventDefault();else onClose()}}><div className={styles.header}><div><p>INTERNAL / CREATOR RECORDS</p><h2 id="creator-work-heading">ประวัติรับงาน · {author}</h2></div><button disabled={busy} onClick={onClose} aria-label="ปิดประวัติรับงาน"><X size={21}/></button></div><div className={styles.content}>{loading?<p role="status" className={styles.notice}>กำลังโหลดประวัติรับงาน…</p>:error?<div className={styles.notice} role="alert">โหลดประวัติไม่สำเร็จ กรุณาปิดและเปิดใหม่</div>:<>
  <p className={styles.notice}>ข้อมูลส่วนนี้สำหรับทีม SHIYA เท่านั้น ไม่แสดงให้ลูกค้าเห็น จำนวนงานอ้างอิงรายการที่ทีมบันทึกไว้</p>
  <div className={styles.stats}>{[{label:'งานที่รับ (ไม่รวมยกเลิก)',value:stats.total,icon:Briefcase},{label:'ส่งงานแล้ว',value:stats.delivered,icon:CheckCircle2},{label:'ยืนยันว่าไม่ส่งงาน',value:stats.missed,icon:AlertTriangle},{label:'รับสินค้า ยังไม่ส่งงาน',value:stats.productOutstanding,icon:Package}].map(stat=><div key={stat.label}><stat.icon size={18}/><span>{stat.label}</span><strong>{stat.value}</strong></div>)}</div>
  <section className={styles.blacklist}><div className={styles.sectionTitle}><h3><ShieldAlert size={18}/>Blacklist / พักการร่วมงาน</h3>{data?.blacklist?.active&&<span>อยู่ใน Blacklist</span>}</div><form onSubmit={event=>{event.preventDefault();void submit('blacklist')}}><label className={styles.check}><input type="checkbox" checked={blacklist} onChange={event=>setBlacklist(event.target.checked)} disabled={busy}/>ทำเครื่องหมาย Blacklist</label><p>เมื่อบันทึก Blacklist ระบบจะซ่อนโปรไฟล์จาก Catalog และไม่อนุญาตให้เผยแพร่จนกว่าจะยกเลิกสถานะนี้</p><label>เหตุผล / ข้อมูลที่ทีมตรวจสอบแล้ว<textarea value={reason} onChange={event=>setReason(event.target.value)} required={blacklist} maxLength={3000} rows={3} placeholder="เช่น แคมเปญที่เกี่ยวข้อง ปัญหาที่พบ และผลการติดตาม" disabled={busy}/></label>{data?.blacklist?.updatedBy&&<small>บันทึกโดย {data.blacklist.updatedBy} · {new Date(data.blacklist.updatedAt).toLocaleString('th-TH')}</small>}<button disabled={busy} className={styles.secondary}>บันทึกสถานะการร่วมงาน</button></form></section>
  <section><div className={styles.sectionTitle}><div><h3>รายการรับงาน</h3><p>บันทึกการรับสินค้าและการส่งงานแยกตามแคมเปญ</p></div><button onClick={()=>setDraft(emptyDraft())} disabled={busy} className={styles.primary}><Plus size={16}/>เพิ่มงาน</button></div>{!data?.records.length?<p className={styles.empty}>ยังไม่มีประวัติรับงาน กด “เพิ่มงาน” เพื่อเริ่มบันทึก</p>:<div className={styles.records}>{[...data.records].reverse().map(record=><article key={record.id}><div className={styles.recordHeader}><div><h4>{record.campaign}</h4><p>{record.brand||'ไม่ได้ระบุแบรนด์'}</p></div><span className={`${styles.workStatus} ${record.status==='missed'?styles.missed:''}`}>{workStatuses[record.status]}</span><button onClick={()=>setDraft({...record})} disabled={busy} aria-label={`แก้ไขงาน ${record.campaign}`}><Pencil size={15}/>แก้ไข</button></div><div className={styles.recordMeta}><span>รับงาน {record.acceptedDate}</span>{record.dueDate&&<span>กำหนดส่ง {record.dueDate}</span>}<span>{record.productReceived?`รับสินค้าแล้ว${record.receivedDate?` · ${record.receivedDate}`:''}`:'ยังไม่ได้รับสินค้า / ไม่มีสินค้า'}</span>{isWorkOverdue(record,today())&&<strong>เกินกำหนดส่ง ยังไม่ส่งงาน</strong>}</div>{record.notes&&<p className={styles.notes}>{record.notes}</p>}{record.evidenceUrl&&<a href={record.evidenceUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>ผลงาน / หลักฐาน</a>}<small>บันทึกโดย {record.updatedBy} · {new Date(record.updatedAt).toLocaleString('th-TH')}</small></article>)}</div>}</section>
  {draft&&<div ref={editor} className={styles.editor}><div className={styles.sectionTitle}><h3>{draft.id?'แก้ไขประวัติรับงาน':'เพิ่มประวัติรับงาน'}</h3><button disabled={busy} onClick={()=>setDraft(null)} aria-label="ปิดฟอร์มรับงาน"><X size={18}/></button></div><form onSubmit={event=>{event.preventDefault();void submit('saveWork')}}><div className={styles.formGrid}><label>ชื่อแคมเปญ *<input value={draft.campaign} onChange={event=>update('campaign',event.target.value)} required maxLength={200}/></label><label>แบรนด์<input value={draft.brand} onChange={event=>update('brand',event.target.value)} maxLength={200}/></label><label>วันที่รับงาน *<input type="date" value={draft.acceptedDate} onChange={event=>update('acceptedDate',event.target.value)} required/></label><label>กำหนดส่งงาน<input type="date" value={draft.dueDate} min={draft.acceptedDate||undefined} onChange={event=>update('dueDate',event.target.value)}/></label><label>สถานะงาน<select value={draft.status} onChange={event=>update('status',event.target.value)}>{Object.entries(workStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>วันที่รับสินค้า<input type="date" value={draft.receivedDate} disabled={!draft.productReceived} onChange={event=>update('receivedDate',event.target.value)}/></label></div><label className={styles.check}><input type="checkbox" checked={draft.productReceived} onChange={event=>update('productReceived',event.target.checked)}/>ได้รับสินค้าหรือของจากแคมเปญแล้ว</label><label>หมายเหตุ / ผลการติดตาม{draft.status==='missed'?' *':''}<textarea value={draft.notes} onChange={event=>update('notes',event.target.value)} required={draft.status==='missed'} maxLength={4000} rows={3} placeholder="ระบุข้อตกลง การติดตาม และผลที่ยืนยันได้"/></label><label>ลิงก์ผลงานหรือหลักฐาน<input type="url" value={draft.evidenceUrl} onChange={event=>update('evidenceUrl',event.target.value)} placeholder="https://…" maxLength={1500}/></label><button disabled={busy} className={styles.primary}>{busy?'กำลังบันทึก…':'บันทึกประวัติรับงาน'}</button></form></div>}
 </>}</div></dialog>;
}
