'use client';
import {useConfirm} from '@/components/admin/ConfirmDialog';
import {useCallback,useEffect,useRef,useState} from 'react';
import CreatorAdminNav from '@/components/admin/CreatorAdminNav';
import CreatorWorkPanel from '@/components/admin/CreatorWorkPanel';
import CreatorsTable from '@/components/admin/CreatorsTable';
import {toast} from 'sonner';
import {Link,useRouter} from '@/navigation';
import {defaultCategories,defaultGenders,type CreatorRecord,type CreatorListRow} from '@/lib/creators';
type Row=Omit<CreatorRecord,'_id'|'createdAt'|'updatedAt'>&{createdAt:string};
const input='mt-1 block w-full rounded-lg border border-slate-200 p-2.5 text-sm';
const button='rounded-lg bg-blue-600 px-4 py-2.5 text-sm text-white disabled:opacity-50';
function download(rows:string[][],name:string){const csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+(/^[=+@\-]/.test(value)?"'"+value:value).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
export default function CreatorsAdmin(){
 const confirmAction=useConfirm();
 const router=useRouter();const [profiles,setProfiles]=useState<CreatorListRow[]>([]),[categories,setCategories]=useState(defaultCategories),[genders,setGenders]=useState(defaultGenders);
 const [loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[canFinance,setCanFinance]=useState(false),[active,setActive]=useState<Row|null>(null),[finance,setFinance]=useState<Record<string,string>|null>(null);
 const [workProfile,setWorkProfile]=useState<CreatorListRow|null>(null);
 const dialogRef=useRef<HTMLDialogElement>(null);
 const loadVersion=useRef(0);
 const loadController=useRef<AbortController|null>(null);
 const activeId=active?.id;
 useEffect(()=>{if(activeId){dialogRef.current?.showModal()}else{dialogRef.current?.close()}},[activeId]);
 const load=useCallback(async()=>{loadController.current?.abort();const controller=new AbortController();loadController.current=controller;const version=++loadVersion.current;setLoading(true);try{const response=await fetch('/api/creators/admin?view=list',{signal:controller.signal});if(response.status===401){router.push('/admin/login');return}if(!response.ok)throw Error();const data=await response.json();if(version!==loadVersion.current)return;setProfiles(data.profiles||[]);setCanFinance(data.canFinance);setCategories(data.profileCategories||defaultCategories);setGenders(data.profileGenders||defaultGenders);setLoaded(true)}catch{if(!controller.signal.aborted)toast.error('โหลดข้อมูลไม่สำเร็จ')}finally{if(version===loadVersion.current)setLoading(false)}},[router]);
 const cancelLoad=useCallback(()=>{loadController.current?.abort();loadVersion.current++},[]);
 useEffect(()=>{void load();return cancelLoad},[load,cancelLoad]);

 const [opening,setOpening]=useState(false),[exporting,setExporting]=useState(false);
 const openVersion=useRef(0);
 const openProfile=async(profile:CreatorListRow)=>{const version=++openVersion.current;setOpening(true);try{const response=await fetch(`/api/creators/admin?id=${encodeURIComponent(profile.id)}`);const data=await response.json();if(!response.ok)throw Error(data.error);if(version!==openVersion.current)return;setActive(data.profile);setFinance(null)}catch(error){toast.error(error instanceof Error?error.message:'เปิดโปรไฟล์ไม่สำเร็จ')}finally{if(version===openVersion.current)setOpening(false)}};
 const exportProfiles=async(rows:CreatorListRow[])=>{setExporting(true);try{const response=await fetch('/api/creators/admin');if(!response.ok)throw Error();const data=await response.json();const ids=new Set(rows.map(row=>row.id));const full:Row[]=data.profiles.filter((profile:Row)=>ids.has(profile.id));download([['ชื่อในวงการ','คำนำหน้า','ชื่อจริง','อีเมล','โทร','LINE','หมวดหมู่','สถานะ','ราคาโพสต์','วิดีโอ','Story','Live','Event'],...full.map(p=>[p.author,p.personal.prefix||'',p.personal.fullName,p.contact.email,p.contact.phone,p.contact.line,p.categories.join(' / '),p.status,...['post','video','story','live','event'].map(key=>p.rates[key]||'')])],'shiya-creators.csv')}catch{toast.error('ส่งออกข้อมูลไม่สำเร็จ')}finally{setExporting(false)}};
 const remove=async(profile:CreatorListRow)=>{if(!await confirmAction(`ลบโปรไฟล์ ${profile.author} ออกจากรายชื่อและหน้า Catalog? ประวัติจะเก็บภายในเพื่อการตรวจสอบ`,{title:'ลบโปรไฟล์',confirmLabel:'ลบโปรไฟล์'}))return;setBusy(true);try{const response=await fetch('/api/creators/admin',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:profile.id})});const result=await response.json();if(!response.ok)throw Error(result.error);setProfiles(previous=>previous.filter(row=>row.id!==profile.id));setActive(null);setWorkProfile(null);setFinance(null);toast.success('ลบโปรไฟล์ออกจากรายชื่อแล้ว')}catch(error){toast.error(error instanceof Error?error.message:'ลบไม่สำเร็จ')}finally{setBusy(false)}};
 const save=async(nextStatus?:Row['status'])=>{if(!active?.author.trim()){toast.error('กรุณากรอกชื่อในวงการ');return}setBusy(true);try{const response=await fetch('/api/creators/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...active,status:nextStatus||active.status})});const result=await response.json();if(!response.ok)throw Error(result.error);setProfiles(previous=>previous.map(profile=>profile.id===active.id?{...active,status:nextStatus||active.status,...(active.img?{photoId:undefined}:{})}:profile));toast.success(nextStatus==='approved'?'อนุมัติและเผยแพร่แล้ว':'บันทึกแล้ว');setActive(null);setFinance(null)}catch(error){toast.error(error instanceof Error?error.message:'บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
 const add=()=>router.push('/admin/creators/new');
 const openFinance=async(id:string)=>{try{const r=await fetch(`/api/creators/finance?id=${encodeURIComponent(id)}`);if(!r.ok)throw Error();setFinance({...await r.json(),creatorId:id})}catch{toast.error('ไม่สามารถเปิดข้อมูลบัญชี/ภาษีได้')}};
 const uploadIdentity=async(file:File)=>{if(!finance)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){toast.error('กรุณาใช้ JPG, PNG หรือ WebP ไม่เกิน 8 MB');return}setBusy(true);try{const body=new FormData();body.set('creatorId',finance.creatorId);body.set('file',file);const response=await fetch('/api/creators/identity',{method:'POST',body});const result=await response.json();if(!response.ok)throw Error(result.error);setFinance(previous=>previous?{...previous,idCardFileId:result.idCardFileId}:previous);toast.success('บันทึกรูปบัตรประชาชนแล้ว')}catch(error){toast.error(error instanceof Error?error.message:'อัปโหลดไม่สำเร็จ')}finally{setBusy(false)}};
 const saveFinance=async()=>{setBusy(true);try{const r=await fetch('/api/creators/finance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(finance)});if(!r.ok)throw Error();toast.success('บันทึกข้อมูลบัญชี/ภาษีแล้ว');setFinance(null)}catch{toast.error('บันทึกไม่สำเร็จ')}finally{setBusy(false)}};

 const update=(field:string,value:unknown)=>setActive(previous=>previous?{...previous,[field]:value}:previous);
 const field=(key:string,label:string,type='text')=><label key={key} className="block text-sm text-slate-800">{label}<input type={type} className={input} value={String(active?.[key as keyof Row]||'')} onChange={e=>update(key,e.target.value)}/></label>;
 const tabs=<CreatorAdminNav/>;
 return <div className="admin-page space-y-6"><div className="admin-page-header flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">จัดการผู้สมัคร Influencer</h1><p className="mt-2 text-sm text-slate-700">ใบสมัคร โปรไฟล์ และคำขอคัดเลือกของลูกค้า — สำหรับทีม SHIYA</p></div><Link href="/influencers/apply" className="text-sm text-blue-600">เปิดฟอร์มสมัคร ↗</Link></div>{loading?<div role="status" className="animate-pulse rounded-2xl border bg-white p-8 text-slate-700">กำลังโหลดรายชื่อผู้สมัคร…</div>:!loaded?<button onClick={load} className={button}>ลองโหลดใหม่</button>:<>
 {<CreatorsTable navigation={tabs} onDelete={remove} profiles={profiles} busy={busy||opening||exporting} onOpen={openProfile} onHistory={profile=>{setWorkProfile(profile);setActive(null);setFinance(null)}} onAdd={add} onExport={exportProfiles}/>}
 {(opening||exporting)&&<p role="status" className="text-sm text-slate-700">{opening?'กำลังเปิดรายละเอียดโปรไฟล์…':'กำลังเตรียมไฟล์ CSV…'}</p>}
 {workProfile&&<CreatorWorkPanel creatorId={workProfile.id} author={workProfile.author} onClose={()=>setWorkProfile(null)} onChange={detail=>setProfiles(previous=>previous.map(profile=>profile.id===detail.creatorId?{...profile,workStats:detail.stats,blacklist:detail.blacklist||undefined,status:detail.profileStatus as Row['status']}:profile))}/>}
 {active&&<dialog ref={dialogRef} onCancel={()=>{setActive(null);setFinance(null)}} className="m-auto max-h-[90dvh] w-[min(960px,94vw)] overflow-y-auto rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-black/50"><section className="p-6 space-y-5"><div className="sticky top-0 z-10 flex flex-wrap items-center justify-between gap-3 border-b bg-white py-4"><h2 className="text-xl font-semibold">ตรวจใบสมัคร: {active.author}</h2>{active.status!=='approved'&&<button disabled={busy} onClick={()=>save('approved')} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'✓ อนุมัติและเผยแพร่'}</button>}<button onClick={()=>{setActive(null);setFinance(null)}} className="text-sm text-slate-700">ปิด</button></div><div className="grid gap-5 md:grid-cols-2">{field('author','ชื่อในวงการ')}{field('img','URL รูปโปรไฟล์ (ถ้าไม่มีไฟล์แนบ)')}<label className="text-sm">สถานะ<select value={active.status} onChange={e=>update('status',e.target.value)} className={input}>{[['pending','รออนุมัติ'],['approved','อนุมัติ / เผยแพร่'],['rejected','ปฏิเสธ'],['hidden','ซ่อน']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">เพศ<select value={active.gender} onChange={e=>update('gender',e.target.value)} className={input}><option value="">ไม่ระบุ</option>{genders.map(value=><option key={value}>{value}</option>)}</select></label></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={active.featured} onChange={e=>update('featured',e.target.checked)}/>Influencer แนะนำ</label><div className="flex flex-wrap gap-3">{categories.map(value=><label key={value} className="flex gap-2 text-sm"><input type="checkbox" checked={active.categories.includes(value)} onChange={()=>update('categories',active.categories.includes(value)?active.categories.filter(v=>v!==value):[...active.categories,value])}/>{value}</label>)}</div><label className="block text-sm">แนะนำตัว<textarea value={active.bio} onChange={e=>update('bio',e.target.value)} rows={3} className={input}/></label>
 <h3 className="font-semibold">Social Media / สถิติ (เผยแพร่หลังอนุมัติ)</h3>{['TikTok','Instagram','Facebook','YouTube','Lemon8'].map(platform=>{const social=active.socials.find(s=>s.platform===platform)||{platform,url:'',followers:'',averageViews:'',engagement:''};return <div key={platform} className="rounded-xl bg-slate-50 p-4"><h4 className="font-medium text-sm mb-3">{platform}</h4><div className="grid gap-3 md:grid-cols-4">{[['url','ลิงก์โปรไฟล์'],['followers','Followers'],['averageViews','Average Views'],['engagement','Engagement (%)']].map(([key,label])=><label key={key} className="text-xs text-slate-700">{label}<input value={social[key as keyof typeof social]} className={input} onChange={e=>update('socials',[...active.socials.filter(s=>s.platform!==platform),{...social,[key]:e.target.value}])}/></label>)}</div></div>})}
 <label className="block text-sm">ลิงก์ผลงาน (หนึ่งลิงก์ต่อบรรทัด)<textarea value={active.portfolio.join('\n')} onChange={e=>update('portfolio',e.target.value.split('\n'))} rows={3} className={input}/></label>{active.mediaKitId&&<a href={`/api/creators/media/${active.mediaKitId}`} className="inline-block text-blue-600 text-sm">ดาวน์โหลด Media Kit (ทีมงานเท่านั้น)</a>}
 <h3 className="font-semibold">ข้อมูลส่วนตัว / ติดต่อ (ไม่เผยแพร่)</h3><div className="grid gap-4 md:grid-cols-2">{[['prefix','คำนำหน้า'],['fullName','ชื่อ–นามสกุล'],['nickname','ชื่อเล่น'],['birthday','วันเกิด'],['province','จังหวัด'],['nationality','สัญชาติ'],['district','อำเภอ / เขต'],['occupation','อาชีพ'],['address','ที่อยู่ติดต่อ'],['otherLanguage','ภาษาอื่น ๆ']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={String(active.personal[key as keyof typeof active.personal]||'')} onChange={e=>update('personal',{...active.personal,[key]:e.target.value})}/></label>)}{[['phone','โทร'],['email','อีเมล'],['line','LINE ID']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={active.contact[key as keyof typeof active.contact]} onChange={e=>update('contact',{...active.contact,[key]:e.target.value})}/></label>)}</div>
 <p className="text-sm text-slate-700">ภาษาที่สื่อสารได้: {active.personal.languages?.join(' · ') || 'ไม่ได้ระบุ'}</p><h3 className="font-semibold">เรทราคา (ทีมงานเท่านั้น)</h3><div className="grid gap-4 md:grid-cols-3">{[['post','โพสต์'],['video','วิดีโอ'],['story','Story'],['live','Live'],['event','Event']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={active.rates[key]||''} onChange={e=>update('rates',{...active.rates,[key]:e.target.value})}/></label>)}</div><p className="text-xs text-slate-700">สมัครเมื่อ {new Date(active.createdAt).toLocaleDateString('th-TH')} · ข้อตกลง: {active.consent.terms?'รับทราบแล้ว':'เพิ่มโดยทีมงาน / ยังไม่มีใบสมัคร'}</p><div className="sticky bottom-0 z-10 flex flex-wrap gap-3 border-t bg-white py-4">{active.status!=='approved'&&<button disabled={busy} onClick={()=>save('approved')} className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'✓ อนุมัติและเผยแพร่'}</button>}{active.status==='pending'&&<button disabled={busy} onClick={()=>save('rejected')} className="rounded-lg border border-red-200 px-4 py-3 text-sm text-red-600 disabled:opacity-50">ไม่อนุมัติ</button>}<button onClick={()=>save()} disabled={busy} className={button}>บันทึกข้อมูลและสถานะ</button><button disabled={busy} onClick={()=>remove(active)} className="rounded-lg bg-red-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">ลบโปรไฟล์</button>{canFinance&&<button onClick={()=>openFinance(active.id)} className="rounded-lg border px-4 py-2 text-sm">บัญชีธนาคาร / ภาษี (Super Admin)</button>}</div>
 {finance&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-semibold mb-5">ข้อมูลบัญชี / ภาษี — เฉพาะ Super Admin</h2><div className="grid gap-4 md:grid-cols-2">{[['bank','ธนาคาร'],['accountName','ชื่อบัญชี'],['accountNumber','เลขบัญชี'],['taxId','เลขผู้เสียภาษี'],['billingAddress','ที่อยู่สำหรับเอกสาร']].map(([key,label])=><label key={key} className="text-sm">{label}<input value={finance[key]||''} className={input} onChange={e=>setFinance({...finance,[key]:e.target.value})}/></label>)}</div><div className="mt-6 rounded-xl border border-amber-200 bg-white p-5"><h3 className="font-semibold text-sm">รูปถ่ายบัตรประชาชน</h3><p className="mt-2 text-xs text-slate-700">เอกสารส่วนตัวที่ผู้สมัครส่งให้ทีมตรวจสอบ เปิดได้เฉพาะ Super Admin และไม่แสดงใน Catalog</p><label className="mt-4 block text-sm">{finance.idCardFileId?'เปลี่ยนรูปบัตรประชาชน':'แนบรูปบัตรประชาชน'} (JPG, PNG, WebP ไม่เกิน 8 MB)<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block text-xs" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadIdentity(file);e.target.value=''}}/></label>{finance.idCardFileId&&<a href={`/api/creators/identity?creatorId=${encodeURIComponent(finance.creatorId)}`} className="mt-4 inline-block text-sm text-blue-600">ดาวน์โหลดเอกสารที่แนบไว้ ↗</a>}</div><button onClick={saveFinance} disabled={busy} className={`${button} mt-5`}>บันทึกข้อมูลจำกัดสิทธิ์</button><button onClick={()=>setFinance(null)} className="ml-4 text-sm">ปิดข้อมูลบัญชี</button></section>}
 </section></dialog>}

 </>}</div>;
}
