'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {toast} from 'sonner';
import {Link,useRouter} from '@/navigation';
import {defaultCategories,defaultGenders,type CreatorRecord} from '@/lib/creators';
type Row=Omit<CreatorRecord,'_id'|'createdAt'|'updatedAt'>&{createdAt:string};
type Selection={_id:string;name:string;email:string;phone:string;company:string;message:string;creators:{id:string;author:string}[];createdAt:string};
const input='mt-1 block w-full rounded-lg border border-slate-200 p-2.5 text-sm';
const button='rounded-lg bg-blue-600 px-4 py-2.5 text-sm text-white disabled:opacity-50';
function download(rows:string[][],name:string){const csv='\uFEFF'+rows.map(row=>row.map(value=>'"'+(/^[=+@\-]/.test(value)?"'"+value:value).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
export default function CreatorsAdmin(){
 const router=useRouter();const [profiles,setProfiles]=useState<Row[]>([]),[selections,setSelections]=useState<Selection[]>([]),[categories,setCategories]=useState(defaultCategories),[genders,setGenders]=useState(defaultGenders),[terms,setTerms]=useState(''),[privacy,setPrivacy]=useState('');
 const [loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[canFinance,setCanFinance]=useState(false),[tab,setTab]=useState('profiles'),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[active,setActive]=useState<Row|null>(null),[finance,setFinance]=useState<Record<string,string>|null>(null);
 const dialogRef=useRef<HTMLDialogElement>(null);
 const loadVersion=useRef(0);
 const activeId=active?.id;
 useEffect(()=>{if(activeId){dialogRef.current?.showModal()}else{dialogRef.current?.close()}},[activeId]);
 const load=useCallback(async()=>{const version=++loadVersion.current;setLoading(true);try{const response=await fetch(tab==='profiles'?'/api/creators/admin':tab==='selections'?'/api/creators/selections':'/api/influencer');if(version!==loadVersion.current)return;if(response.status===401){toast.error('กรุณาเข้าสู่ระบบใหม่เพื่อยืนยันสิทธิ์');router.push('/admin/login');return}if(!response.ok)throw Error();const data=await response.json();if(version!==loadVersion.current)return;if(tab==='profiles'){setProfiles(data.profiles||[]);setCanFinance(data.canFinance)}else if(tab==='selections'){setSelections(data)}else{setCategories(data.profileCategories||defaultCategories);setGenders(data.profileGenders||defaultGenders);setTerms(data.applicantTerms||'');setPrivacy(data.applicantPrivacy||'')}setLoaded(true)}catch{if(version===loadVersion.current)toast.error('โหลดข้อมูลไม่สำเร็จ')}finally{if(version===loadVersion.current)setLoading(false)}},[router,tab]);
 useEffect(()=>{void load()},[load]);
 const save=async(nextStatus?:Row['status'])=>{if(!active?.author.trim()){toast.error('กรุณากรอกชื่อในวงการ');return}setBusy(true);try{const response=await fetch('/api/creators/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...active,status:nextStatus||active.status})});const result=await response.json();if(!response.ok)throw Error(result.error);setProfiles(previous=>previous.map(profile=>profile.id===active.id?{...active,status:nextStatus||active.status,...(active.img?{photoId:undefined}:{})}:profile));toast.success(nextStatus==='approved'?'อนุมัติและเผยแพร่แล้ว':'บันทึกแล้ว');setActive(null);setFinance(null)}catch(error){toast.error(error instanceof Error?error.message:'บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
 const configure=async()=>{setBusy(true);try{const response=await fetch('/api/influencer',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileCategories:[...new Set(categories.map(v=>v.trim()).filter(Boolean))],profileGenders:[...new Set(genders.map(v=>v.trim()).filter(Boolean))],applicantTerms:terms,applicantPrivacy:privacy})});if(!response.ok)throw Error();toast.success('บันทึกการตั้งค่าแล้ว')}catch{toast.error('บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
 const add=async()=>{setBusy(true);try{const r=await fetch('/api/creators/admin',{method:'POST'});if(!r.ok)throw Error();const result=await r.json();setProfiles(previous=>[result.profile,...previous]);setActive(result.profile)}catch{toast.error('เพิ่มโปรไฟล์ไม่สำเร็จ')}finally{setBusy(false)}};
 const openFinance=async(id:string)=>{try{const r=await fetch(`/api/creators/finance?id=${encodeURIComponent(id)}`);if(!r.ok)throw Error();setFinance({...await r.json(),creatorId:id})}catch{toast.error('ไม่สามารถเปิดข้อมูลบัญชี/ภาษีได้')}};
 const uploadIdentity=async(file:File)=>{if(!finance)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){toast.error('กรุณาใช้ JPG, PNG หรือ WebP ไม่เกิน 8 MB');return}setBusy(true);try{const body=new FormData();body.set('creatorId',finance.creatorId);body.set('file',file);const response=await fetch('/api/creators/identity',{method:'POST',body});const result=await response.json();if(!response.ok)throw Error(result.error);setFinance(previous=>previous?{...previous,idCardFileId:result.idCardFileId}:previous);toast.success('บันทึกรูปบัตรประชาชนแล้ว')}catch(error){toast.error(error instanceof Error?error.message:'อัปโหลดไม่สำเร็จ')}finally{setBusy(false)}};
 const saveFinance=async()=>{setBusy(true);try{const r=await fetch('/api/creators/finance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(finance)});if(!r.ok)throw Error();toast.success('บันทึกข้อมูลบัญชี/ภาษีแล้ว');setFinance(null)}catch{toast.error('บันทึกไม่สำเร็จ')}finally{setBusy(false)}};
 const filtered=profiles.filter(p=>(status==='all'||p.status===status)&&[p.author,p.personal.fullName,p.contact.email].join(' ').toLowerCase().includes(query.toLowerCase()));
 const update=(field:string,value:unknown)=>setActive(previous=>previous?{...previous,[field]:value}:previous);
 const field=(key:string,label:string,type='text')=><label key={key} className="block text-sm text-slate-600">{label}<input type={type} className={input} value={String(active?.[key as keyof Row]||'')} onChange={e=>update(key,e.target.value)}/></label>;
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">จัดการผู้สมัคร Influencer</h1><p className="mt-2 text-sm text-slate-500">ใบสมัคร โปรไฟล์ และคำขอคัดเลือกของลูกค้า — สำหรับทีม SHIYA</p></div><Link href="/influencers/apply" className="text-sm text-blue-600">เปิดฟอร์มสมัคร ↗</Link></div><div className="flex flex-wrap gap-2">{[['profiles','ผู้สมัครและโปรไฟล์'],['selections','รายชื่อที่ลูกค้าเลือก'],['settings','หมวดหมู่ / ข้อตกลง']].map(([value,label])=><button key={value} onClick={()=>{if(value===tab)return;setLoading(true);setTab(value);setActive(null);setFinance(null)}} className={`rounded-xl px-4 py-3 text-sm ${tab===value?'bg-black text-white':'bg-white border'}`}>{label}</button>)}</div>{loading?<div role="status" className="animate-pulse rounded-2xl border bg-white p-8 text-slate-500">กำลังโหลด{tab==='profiles'?'รายชื่อผู้สมัคร':tab==='selections'?'คำขอจากลูกค้า':'การตั้งค่า'}…</div>:!loaded?<button onClick={load} className={button}>ลองโหลดใหม่</button>:<>
 {tab==='profiles'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['pending','รอพิจารณา'],['approved','เผยแพร่แล้ว'],['rejected','ไม่ผ่าน'],['hidden','ซ่อนอยู่']].map(([value,label])=><button key={value} onClick={()=>setStatus(value)} className={`rounded-2xl border p-5 text-left ${status===value?'border-blue-500 bg-blue-50':'bg-white'}`}><span className="text-sm text-slate-500">{label}</span><strong className="mt-2 block text-3xl">{profiles.filter(p=>p.status===value).length}</strong></button>)}</div><div className="flex flex-wrap gap-3"><input aria-label="ค้นหาผู้สมัคร" placeholder="ค้นหาชื่อหรืออีเมล" value={query} onChange={e=>setQuery(e.target.value)} className="rounded-xl border p-3 text-sm"/><select aria-label="สถานะผู้สมัคร" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-3 text-sm"><option value="all">ทั้งหมด ({profiles.length})</option>{[['pending','รออนุมัติ'],['approved','อนุมัติแล้ว'],['rejected','ปฏิเสธ'],['hidden','ซ่อน']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button onClick={add} disabled={busy} className={button}>+ เพิ่มโปรไฟล์โดยทีมงาน</button><button className="rounded-xl border px-4 text-sm" onClick={()=>download([['ชื่อในวงการ','คำนำหน้า','ชื่อจริง','อีเมล','โทร','LINE','หมวดหมู่','สถานะ','ราคาโพสต์','วิดีโอ','Story','Live','Event'],...filtered.map(p=>[p.author,p.personal.prefix||'',p.personal.fullName,p.contact.email,p.contact.phone,p.contact.line,p.categories.join(' / '),p.status,...['post','video','story','live','event'].map(key=>p.rates[key]||'')])],'shiya-creators.csv')}>ส่งออก CSV สำหรับ Campaign</button></div><p className="text-xs text-slate-500">CSV รวมข้อมูลติดต่อและเรทราคา ไม่มีข้อมูลบัญชีธนาคารหรือภาษี</p><div className="grid gap-4 lg:grid-cols-2">{filtered.map(profile=><button key={profile.id} onClick={()=>{setActive(structuredClone(profile));setFinance(null)}} className="flex items-center gap-4 rounded-2xl border bg-white p-5 text-left">{(profile.photoId||profile.img)&&<Image width={64} height={80} unoptimized src={profile.photoId?`/api/creators/media/${profile.photoId}`:profile.img} alt="" className="h-20 w-16 rounded-lg object-cover"/>}<div><h2 className="font-semibold">{profile.author}{profile.featured?' ★':''}</h2><p className="text-sm text-slate-500 mt-1">{profile.categories.join(' · ')}</p><p className="text-sm mt-2 font-medium text-blue-600">{{pending:'รออนุมัติ',approved:'อนุมัติแล้ว',rejected:'ปฏิเสธ',hidden:'ซ่อน'}[profile.status]}</p><p className="mt-2 text-xs text-slate-500">คลิกเพื่อตรวจใบสมัครและอนุมัติ →</p></div></button>)}</div>{!filtered.length&&<p className="rounded-2xl bg-white p-8 text-slate-500">ยังไม่มีผู้สมัครในรายการนี้</p>}</>}
 {active&&<dialog ref={dialogRef} onCancel={()=>{setActive(null);setFinance(null)}} className="m-auto max-h-[90dvh] w-[min(960px,94vw)] overflow-y-auto rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-black/50"><section className="p-6 space-y-5"><div className="sticky top-0 z-10 flex flex-wrap items-center justify-between gap-3 border-b bg-white py-4"><h2 className="text-xl font-semibold">ตรวจใบสมัคร: {active.author}</h2>{active.status!=='approved'&&<button disabled={busy} onClick={()=>save('approved')} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'✓ อนุมัติและเผยแพร่'}</button>}<button onClick={()=>{setActive(null);setFinance(null)}} className="text-sm text-slate-500">ปิด</button></div><div className="grid gap-5 md:grid-cols-2">{field('author','ชื่อในวงการ')}{field('img','URL รูปโปรไฟล์ (ถ้าไม่มีไฟล์แนบ)')}<label className="text-sm">สถานะ<select value={active.status} onChange={e=>update('status',e.target.value)} className={input}>{[['pending','รออนุมัติ'],['approved','อนุมัติ / เผยแพร่'],['rejected','ปฏิเสธ'],['hidden','ซ่อน']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">เพศ<select value={active.gender} onChange={e=>update('gender',e.target.value)} className={input}><option value="">ไม่ระบุ</option>{genders.map(value=><option key={value}>{value}</option>)}</select></label></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={active.featured} onChange={e=>update('featured',e.target.checked)}/>Influencer แนะนำ</label><div className="flex flex-wrap gap-3">{categories.map(value=><label key={value} className="flex gap-2 text-sm"><input type="checkbox" checked={active.categories.includes(value)} onChange={()=>update('categories',active.categories.includes(value)?active.categories.filter(v=>v!==value):[...active.categories,value])}/>{value}</label>)}</div><label className="block text-sm">แนะนำตัว<textarea value={active.bio} onChange={e=>update('bio',e.target.value)} rows={3} className={input}/></label>
 <h3 className="font-semibold">Social Media / สถิติ (เผยแพร่หลังอนุมัติ)</h3>{['TikTok','Instagram','Facebook','YouTube','Lemon8'].map(platform=>{const social=active.socials.find(s=>s.platform===platform)||{platform,url:'',followers:'',averageViews:'',engagement:''};return <div key={platform} className="rounded-xl bg-slate-50 p-4"><h4 className="font-medium text-sm mb-3">{platform}</h4><div className="grid gap-3 md:grid-cols-4">{[['url','ลิงก์โปรไฟล์'],['followers','Followers'],['averageViews','Average Views'],['engagement','Engagement (%)']].map(([key,label])=><label key={key} className="text-xs text-slate-500">{label}<input value={social[key as keyof typeof social]} className={input} onChange={e=>update('socials',[...active.socials.filter(s=>s.platform!==platform),{...social,[key]:e.target.value}])}/></label>)}</div></div>})}
 <label className="block text-sm">ลิงก์ผลงาน (หนึ่งลิงก์ต่อบรรทัด)<textarea value={active.portfolio.join('\n')} onChange={e=>update('portfolio',e.target.value.split('\n'))} rows={3} className={input}/></label>{active.mediaKitId&&<a href={`/api/creators/media/${active.mediaKitId}`} className="inline-block text-blue-600 text-sm">ดาวน์โหลด Media Kit (ทีมงานเท่านั้น)</a>}
 <h3 className="font-semibold">ข้อมูลส่วนตัว / ติดต่อ (ไม่เผยแพร่)</h3><div className="grid gap-4 md:grid-cols-2">{[['prefix','คำนำหน้า'],['fullName','ชื่อ–นามสกุล'],['nickname','ชื่อเล่น'],['birthday','วันเกิด'],['province','จังหวัด'],['nationality','สัญชาติ'],['district','อำเภอ / เขต'],['occupation','อาชีพ'],['address','ที่อยู่ติดต่อ'],['otherLanguage','ภาษาอื่น ๆ']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={String(active.personal[key as keyof typeof active.personal]||'')} onChange={e=>update('personal',{...active.personal,[key]:e.target.value})}/></label>)}{[['phone','โทร'],['email','อีเมล'],['line','LINE ID']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={active.contact[key as keyof typeof active.contact]} onChange={e=>update('contact',{...active.contact,[key]:e.target.value})}/></label>)}</div>
 <p className="text-sm text-slate-500">ภาษาที่สื่อสารได้: {active.personal.languages?.join(' · ') || 'ไม่ได้ระบุ'}</p><h3 className="font-semibold">เรทราคา (ทีมงานเท่านั้น)</h3><div className="grid gap-4 md:grid-cols-3">{[['post','โพสต์'],['video','วิดีโอ'],['story','Story'],['live','Live'],['event','Event']].map(([key,label])=><label key={key} className="text-sm">{label}<input className={input} value={active.rates[key]||''} onChange={e=>update('rates',{...active.rates,[key]:e.target.value})}/></label>)}</div><p className="text-xs text-slate-500">สมัครเมื่อ {new Date(active.createdAt).toLocaleDateString('th-TH')} · ข้อตกลง: {active.consent.terms?'รับทราบแล้ว':'เพิ่มโดยทีมงาน / ยังไม่มีใบสมัคร'}</p><div className="sticky bottom-0 z-10 flex flex-wrap gap-3 border-t bg-white py-4">{active.status!=='approved'&&<button disabled={busy} onClick={()=>save('approved')} className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก…':'✓ อนุมัติและเผยแพร่'}</button>}{active.status==='pending'&&<button disabled={busy} onClick={()=>save('rejected')} className="rounded-lg border border-red-200 px-4 py-3 text-sm text-red-600 disabled:opacity-50">ไม่อนุมัติ</button>}<button onClick={()=>save()} disabled={busy} className={button}>บันทึกข้อมูลและสถานะ</button>{canFinance&&<button onClick={()=>openFinance(active.id)} className="rounded-lg border px-4 py-2 text-sm">บัญชีธนาคาร / ภาษี (Super Admin)</button>}</div>
 {finance&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-semibold mb-5">ข้อมูลบัญชี / ภาษี — เฉพาะ Super Admin</h2><div className="grid gap-4 md:grid-cols-2">{[['bank','ธนาคาร'],['accountName','ชื่อบัญชี'],['accountNumber','เลขบัญชี'],['taxId','เลขผู้เสียภาษี'],['billingAddress','ที่อยู่สำหรับเอกสาร']].map(([key,label])=><label key={key} className="text-sm">{label}<input value={finance[key]||''} className={input} onChange={e=>setFinance({...finance,[key]:e.target.value})}/></label>)}</div><div className="mt-6 rounded-xl border border-amber-200 bg-white p-5"><h3 className="font-semibold text-sm">รูปถ่ายบัตรประชาชน</h3><p className="mt-2 text-xs text-slate-500">เอกสารส่วนตัวที่ผู้สมัครส่งให้ทีมตรวจสอบ เปิดได้เฉพาะ Super Admin และไม่แสดงใน Catalog</p><label className="mt-4 block text-sm">{finance.idCardFileId?'เปลี่ยนรูปบัตรประชาชน':'แนบรูปบัตรประชาชน'} (JPG, PNG, WebP ไม่เกิน 8 MB)<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block text-xs" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadIdentity(file);e.target.value=''}}/></label>{finance.idCardFileId&&<a href={`/api/creators/identity?creatorId=${encodeURIComponent(finance.creatorId)}`} className="mt-4 inline-block text-sm text-blue-600">ดาวน์โหลดเอกสารที่แนบไว้ ↗</a>}</div><button onClick={saveFinance} disabled={busy} className={`${button} mt-5`}>บันทึกข้อมูลจำกัดสิทธิ์</button><button onClick={()=>setFinance(null)} className="ml-4 text-sm">ปิดข้อมูลบัญชี</button></section>}
 </section></dialog>}
 {tab==='selections'&&<><button className={button} onClick={()=>download([['วันที่','ลูกค้า','บริษัท','Email','โทร','Influencer','รายละเอียด'],...selections.map(s=>[s.createdAt,s.name,s.company,s.email,s.phone,s.creators.map(p=>p.author).join(' / '),s.message])],'shiya-creator-requests.csv')}>ส่งออกคำขอ CSV</button>{selections.map(s=><article key={s._id} className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">{s.name} / {s.company||'ไม่ระบุบริษัท'}</h2><p className="text-sm text-slate-500 mt-2">{s.email} · {s.phone}</p><p className="mt-4 text-blue-600">{s.creators.map(p=>p.author).join(' · ')}</p><p className="mt-3 whitespace-pre-line text-sm">{s.message}</p><p className="text-xs text-slate-400 mt-4">{new Date(s.createdAt).toLocaleString('th-TH')}</p></article>)}{!selections.length&&<p className="rounded-2xl bg-white p-8 text-slate-500">ยังไม่มีคำขอจากลูกค้า</p>}</>}
 {tab==='settings'&&<><div className="grid gap-5 md:grid-cols-2">{[{title:'หมวดหมู่อินฟลูเอนเซอร์',values:categories,set:setCategories},{title:'ตัวเลือกเพศ',values:genders,set:setGenders}].map(group=><section key={group.title} className="rounded-2xl border bg-white p-5"><h2 className="font-semibold mb-4">{group.title}</h2><div className="space-y-2">{group.values.map((value,index)=><div key={index} className="flex gap-2"><input aria-label={`${group.title} ${index+1}`} value={value} onChange={e=>group.set(previous=>previous.map((v,i)=>i===index?e.target.value:v))} className="min-w-0 flex-1 rounded-lg border p-2"/><button onClick={()=>group.set(previous=>previous.filter((_,i)=>i!==index))} className="text-red-500 text-sm">ลบ</button></div>)}</div><button onClick={()=>group.set(previous=>[...previous,''])} className="mt-3 text-blue-600 text-sm">+ เพิ่มตัวเลือก</button></section>)}</div><section className="rounded-2xl border bg-white p-6 space-y-5"><label className="block text-sm">เงื่อนไขการสมัคร (เว้นว่างใช้ข้อความเริ่มต้น)<textarea value={terms} onChange={e=>setTerms(e.target.value)} rows={5} className={input}/></label><label className="block text-sm">Privacy Notice (เว้นว่างใช้ข้อความเริ่มต้น)<textarea value={privacy} onChange={e=>setPrivacy(e.target.value)} rows={6} className={input}/></label><button disabled={busy} onClick={configure} className={button}>บันทึกการตั้งค่า</button></section></>}
 </>}</div>;
}
