'use client';
import {useConfirm} from '@/components/admin/ConfirmDialog';
import {useCallback,useEffect,useState} from 'react';
import {MessageSquare,Mail,Trash2,Search,Calendar,RefreshCw,ArrowUpRight,X,Inbox,Clock,CheckCircle2,AlertCircle} from 'lucide-react';
import {toast} from 'sonner';
import styles from './Contacts.module.css';
interface Contact{_id:string;name:string;email:string;services:string[];message:string;status:'unread'|'read'|'replied';createdAt:string}
const statusLabels={unread:'ยังไม่ได้อ่าน',read:'อ่านแล้ว',replied:'ตอบกลับแล้ว'};
function dateLabel(value:string,full=false){const date=new Date(value);if(Number.isNaN(date.getTime()))return 'ไม่ระบุวันที่';return full?date.toLocaleString('th-TH',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('th-TH',{day:'numeric',month:'short'})}
export default function ContactsAdminPage(){
 const confirmAction=useConfirm();
 const [contacts,setContacts]=useState<Contact[]>([]);const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [selectedContact,setSelectedContact]=useState<Contact|null>(null);const [deleting,setDeleting]=useState<string|null>(null);
 const fetchContacts=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const response=await fetch('/api/contacts',{signal,cache:'no-store'});if(!response.ok)throw Error();const result=await response.json();if(signal?.aborted)return;setContacts(result);setSelectedContact(previous=>previous?result.find((contact:Contact)=>contact._id===previous._id)||null:null);setError(false)}catch{if(!signal?.aborted){setError(true);toast.error('โหลดข้อความไม่สำเร็จ')}}finally{if(!signal?.aborted)setLoading(false)}},[]);
 useEffect(()=>{const controller=new AbortController();void fetchContacts(controller.signal);return()=>controller.abort()},[fetchContacts]);
 useEffect(()=>{if(selectedContact&&window.matchMedia('(max-width:1023px)').matches)document.getElementById('admin-contact-detail')?.scrollIntoView({block:'start'})},[selectedContact]);
 const handleDelete=async(id:string)=>{if(deleting||!await confirmAction('ต้องการลบข้อความนี้ใช่ไหม?'))return;setDeleting(id);try{const response=await fetch(`/api/contacts?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!response.ok)throw Error();setContacts(previous=>previous.filter(contact=>contact._id!==id));setSelectedContact(previous=>previous?._id===id?null:previous);toast.success('ลบข้อความแล้ว')}catch{toast.error('ลบข้อความไม่สำเร็จ')}finally{setDeleting(null)}};
 const visibleContacts=contacts.filter(contact=>(filter==='all'||contact.status===filter)&&[contact.name,contact.email,contact.message,...(contact.services||[])].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 return <div className={`admin-page ${styles.page}`}>
  <div className={styles.heading}><div><p className={styles.eyebrow}>CLIENT INBOX</p><h1>ข้อความจากลูกค้า</h1><p className={styles.subtitle}>ทุกการติดต่อ คือจุดเริ่มต้นของผลงานถัดไป</p></div><button className={styles.refresh} onClick={()=>fetchContacts()} disabled={loading}><RefreshCw size={16} className={loading?styles.spin:undefined}/>รีเฟรชข้อความ</button></div>
  <section className={styles.stats} aria-label="สรุปข้อความจากลูกค้า">{[{label:'ข้อความทั้งหมด',count:contacts.length,icon:Inbox,color:'blue',filter:'all'},{label:'ยังไม่ได้อ่าน',count:contacts.filter(c=>c.status==='unread').length,icon:Clock,color:'amber',filter:'unread'},{label:'ตอบกลับแล้ว',count:contacts.filter(c=>c.status==='replied').length,icon:CheckCircle2,color:'green',filter:'replied'}].map(stat=><button key={stat.label} onClick={()=>setFilter(stat.filter)} aria-pressed={filter===stat.filter} className={`${styles.stat} ${filter===stat.filter?styles.activeStat:''}`}><span className={`${styles.statIcon} ${styles[stat.color]}`}><stat.icon size={21}/></span><span><span className={styles.statLabel}>{stat.label}</span><strong>{loading&&!contacts.length?'—':stat.count}</strong></span></button>)}</section>
  {error&&<div className={styles.error} role="alert"><AlertCircle size={18}/><span>โหลดข้อมูลไม่สำเร็จ{contacts.length?' กำลังแสดงข้อความที่โหลดไว้ก่อนหน้า':''}</span><button onClick={()=>fetchContacts()} disabled={loading}>ลองใหม่</button></div>}
  <div className={styles.workspace}>
   <section className={styles.inbox} aria-labelledby="inbox-heading"><div className={styles.inboxTop}><div className={styles.inboxTitle}><h2 id="inbox-heading">กล่องข้อความ</h2><span>{visibleContacts.length} รายการ</span></div><label className={styles.search}><Search size={17}/><input type="search" placeholder="ค้นหาชื่อ อีเมล หรือข้อความ…" aria-label="ค้นหาข้อความจากลูกค้า" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className={styles.filters} aria-label="กรองตามสถานะ">{[['all','ทั้งหมด'],['unread','ยังไม่อ่าน'],['read','อ่านแล้ว'],['replied','ตอบกลับแล้ว']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)} className={filter===value?styles.activeFilter:undefined}>{label}</button>)}</div></div>
    <div className={styles.messageList} aria-busy={loading}>{loading&&!contacts.length?<div className={styles.listLoading} role="status">กำลังโหลดข้อความ…{[0,1,2].map(i=><div key={i}/>)}</div>:visibleContacts.length?visibleContacts.map(contact=><button key={contact._id} onClick={()=>setSelectedContact(contact)} aria-pressed={selectedContact?._id===contact._id} className={`${styles.message} ${selectedContact?._id===contact._id?styles.activeMessage:''}`}><div className={styles.messageTop}><span className={styles.avatar}>{contact.name?.trim().charAt(0)||'?'}</span><div><h3>{contact.name}</h3><p>{contact.email}</p></div><time dateTime={contact.createdAt}>{dateLabel(contact.createdAt)}</time></div><p className={styles.excerpt}>{contact.message||'ไม่ได้ระบุข้อความเพิ่มเติม'}</p><div className={styles.messageBottom}><div className={styles.tags}>{(contact.services||[]).slice(0,2).map((service,index)=><span key={`${service}-${index}`}>{service}</span>)}{(contact.services?.length||0)>2&&<span>+{contact.services.length-2}</span>}</div>{contact.status==='unread'&&<span className={styles.unreadDot} aria-label="ยังไม่ได้อ่าน"/>}</div></button>):<div className={styles.emptyList}><Search size={28}/><h3>{query||filter!=='all'?'ไม่พบข้อความที่ตรงกัน':'ยังไม่มีข้อความจากลูกค้า'}</h3><p>{query||filter!=='all'?'ลองเปลี่ยนคำค้นหาหรือเลือกดูทั้งหมด':'ข้อความจากหน้า Contact จะปรากฏที่นี่'}</p>{(query||filter!=='all')&&<button onClick={()=>{setQuery('');setFilter('all')}}>แสดงทั้งหมด</button>}</div>}</div>
   </section>
   <section id="admin-contact-detail" className={styles.detail} aria-label="รายละเอียดข้อความ">{selectedContact?<>
    <div className={styles.detailTop}><span className={styles.detailEyebrow}>MESSAGE DETAILS</span><button onClick={()=>setSelectedContact(null)} aria-label="ปิดรายละเอียดข้อความ"><X size={18}/></button></div><div className={styles.sender}><span className={styles.senderAvatar}>{selectedContact.name?.trim().charAt(0)||'?'}</span><div><h2>{selectedContact.name}</h2><a href={`mailto:${selectedContact.email}`}>{selectedContact.email}</a></div></div>
    <div className={styles.metadata}><span><Calendar size={15}/>{dateLabel(selectedContact.createdAt,true)}</span><span className={`${styles.status} ${selectedContact.status==='unread'?styles.amber:selectedContact.status==='replied'?styles.green:styles.blue}`}>{statusLabels[selectedContact.status]||'ไม่ระบุสถานะ'}</span></div>
    {(selectedContact.services?.length||0)>0&&<div className={styles.interests}><h3>บริการที่สนใจ</h3><div>{selectedContact.services.map((service,index)=><span key={`${service}-${index}`}>{service}</span>)}</div></div>}
    <div className={styles.body}><h3>ข้อความจากลูกค้า</h3><div>{selectedContact.message||'ไม่ได้ระบุข้อความเพิ่มเติม'}</div></div>
    <div className={styles.detailFooter}><a href={`mailto:${selectedContact.email}`} className={styles.reply}><Mail size={17}/>ตอบกลับทางอีเมล<ArrowUpRight size={16}/></a><button onClick={()=>handleDelete(selectedContact._id)} disabled={deleting!==null} className={styles.delete}><Trash2 size={16}/>{deleting===selectedContact._id?'กำลังลบ…':'ลบข้อความ'}</button></div>
   </>:<div className={styles.emptyDetail}><span><MessageSquare size={31}/></span><p className={styles.eyebrow}>LET’S START A CONVERSATION</p><h2>เลือกข้อความเพื่ออ่านรายละเอียด</h2><p>เปิดดูสิ่งที่ลูกค้าต้องการ<br/>แล้วเริ่มต้นวางแผนงานไปด้วยกัน</p><div><Mail size={15}/>ข้อมูลติดต่อและบริการที่สนใจจะแสดงที่นี่</div></div>}</section>
  </div>
 </div>;
}
