'use client';
import {useCallback,useEffect,useState} from 'react';
import {useLocale} from 'next-intl';
import Link from 'next/link';
import {AppWindow,Layers,FolderOpen,Globe,Video,ArrowUpRight,RefreshCw,CheckCircle2,AlertCircle,Clock,Database,Activity,Users,MessageSquare,Receipt,Film,ChevronRight} from 'lucide-react';
import styles from './Dashboard.module.css';
interface DashboardData{
 sections:{hero:{slides:number;lastUpdated:string|null};services:{count:number;lastUpdated:string|null};projects:{count:number;lastUpdated:string|null};clients:{count:number;lastUpdated:string|null};influencer:{items:number;categories:number;lastUpdated:string|null}};
 totals:{totalSections:number;totalItems:number;lastModified:string|null;configuredSections:number};
}
function timeAgo(value:string|null){
 if(!value)return 'ยังไม่มีวันที่อัปเดต';
 const date=new Date(value);if(Number.isNaN(date.getTime()))return 'ยังไม่มีวันที่อัปเดต';
 const minutes=Math.max(0,Math.floor((Date.now()-date.getTime())/60000));
 if(minutes<1)return 'เมื่อสักครู่';if(minutes<60)return `${minutes} นาทีที่แล้ว`;if(minutes<1440)return `${Math.floor(minutes/60)} ชั่วโมงที่แล้ว`;return `${Math.floor(minutes/1440)} วันที่แล้ว`;
}
const sections=[
 {key:'hero',title:'ภาพและวิดีโอหน้าแรก',description:'แบนเนอร์และข้อความเปิดเว็บไซต์',icon:AppWindow,color:'blue',info:(d:DashboardData)=>`${d.sections.hero.slides} สไลด์`},
 {key:'services',title:'บริการของสตูดิโอ',description:'ชื่อบริการ รายละเอียด และภาพปก',icon:Layers,color:'purple',info:(d:DashboardData)=>`${d.sections.services.count} บริการ`},
 {key:'projects',title:'แกลเลอรีโปรเจกต์',description:'โฟลเดอร์ผลงาน รูปภาพ และวิดีโอ',icon:FolderOpen,color:'amber',info:(d:DashboardData)=>`${d.sections.projects.count} โปรเจกต์`},
 {key:'clients',title:'ลูกค้าและพาร์ตเนอร์',description:'ชื่อแบรนด์และโลโก้บนเว็บไซต์',icon:Globe,color:'green',info:(d:DashboardData)=>`${d.sections.clients.count} แบรนด์`},
 {key:'influencer',title:'Influencer & Commerce',description:'เนื้อหาและหมวดหมู่ในหน้าเว็บไซต์',icon:Video,color:'pink',info:(d:DashboardData)=>`${d.sections.influencer.items} รายการ · ${d.sections.influencer.categories} หมวด`},
] as const;
const shortcuts=[{path:'creators',title:'ตรวจใบสมัคร Influencer',description:'พิจารณาและจัดการโปรไฟล์ครีเอเตอร์',icon:Users},{path:'contacts',title:'ข้อความจากลูกค้า',description:'เปิดดูรายละเอียดและข้อมูลติดต่อ',icon:MessageSquare},{path:'quotations',title:'จัดการใบเสนอราคา',description:'สร้าง แก้ไข และพิมพ์ใบเสนอราคา',icon:Receipt},{path:'service-works',title:'ผลงานแยกตามบริการ',description:'เพิ่มหรือแก้ไขแคมเปญของแต่ละบริการ',icon:Film}];
export default function AdminDashboard(){
 const locale=useLocale();const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [refreshing,setRefreshing]=useState(false);
 const fetchData=useCallback(async(signal?:AbortSignal)=>{try{const response=await fetch('/api/dashboard',{signal,cache:'no-store'});if(!response.ok)throw Error();const result=await response.json();if(signal?.aborted)return;setData(result);setError(false)}catch{if(!signal?.aborted)setError(true)}finally{if(!signal?.aborted){setLoading(false);setRefreshing(false)}}},[]);
 useEffect(()=>{const controller=new AbortController();void fetchData(controller.signal);return()=>controller.abort()},[fetchData]);
 const handleRefresh=()=>{setRefreshing(true);void fetchData()};
 const recent=data?sections.filter(section=>data.sections[section.key].lastUpdated).sort((a,b)=>new Date(data.sections[b.key].lastUpdated!).getTime()-new Date(data.sections[a.key].lastUpdated!).getTime()):[];
 const progress=data?Math.round(data.totals.configuredSections/Math.max(1,data.totals.totalSections)*100):0;
 return <div className={`admin-page ${styles.dashboard}`}>
  <div className={styles.heading}><div><p className={styles.eyebrow}>YOUR WORKSPACE</p><h1>ภาพรวมเว็บไซต์</h1><p className={styles.subtitle}>จัดการเนื้อหาและงานของทีม SHIYA จากที่เดียว</p></div><button onClick={handleRefresh} disabled={loading||refreshing} className={styles.refresh}><RefreshCw size={16} className={refreshing?styles.spin:undefined}/>{refreshing?'กำลังรีเฟรช…':'รีเฟรชข้อมูล'}</button></div>
  <section className={styles.welcome}><div><span className={styles.welcomeLabel}>SHIYA STUDIO / ADMIN</span><h2>พร้อมสร้างผลงาน<br/>ที่คนจดจำ</h2><p>ดูแลเว็บไซต์ให้เป็นปัจจุบัน แล้วเดินหน้าสู่แคมเปญถัดไป</p><a href={`/${locale}`} target="_blank" rel="noopener noreferrer">เปิดเว็บไซต์<ArrowUpRight size={17}/></a></div><div className={styles.welcomeStatus}><span className={`${styles.status} ${error?styles.statusError:''}`} role="status">{error?<AlertCircle size={14}/>:<CheckCircle2 size={14}/>} {loading?'กำลังโหลดข้อมูล':refreshing?'กำลังอัปเดตข้อมูล':error?'โหลดข้อมูลไม่สำเร็จ':'โหลดข้อมูลล่าสุดแล้ว'}</span><div className={styles.setup}><span>ส่วนเว็บไซต์ที่บันทึกข้อมูลแล้ว</span><strong>{data?`${data.totals.configuredSections}`:'—'}<small>/ {data?.totals.totalSections??'—'}</small></strong><div className={styles.progress} role="progressbar" aria-label="ส่วนเว็บไซต์ที่ตั้งค่าแล้ว" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{width:`${progress}%`}}/></div><p>{data?`${progress}% ของส่วนเนื้อหาเว็บไซต์`:'กำลังตรวจข้อมูล…'}</p></div></div></section>
  {error&&<div className={styles.error} role="alert"><AlertCircle size={19}/><p>{data?'รีเฟรชไม่สำเร็จ กำลังแสดงข้อมูลที่โหลดไว้ก่อนหน้า':'โหลดข้อมูลภาพรวมไม่สำเร็จ กรุณาลองอีกครั้ง'}</p><button onClick={handleRefresh} disabled={refreshing}>ลองใหม่</button></div>}
  <section className={styles.metrics} aria-label="สรุปข้อมูลเว็บไซต์">
   {[{label:'รายการเนื้อหาทั้งหมด',value:data?String(data.totals.totalItems):'—',detail:'รวมรายการใน 5 ส่วนเว็บไซต์',icon:Database,color:'blue'},{label:'ส่วนเนื้อหาเว็บไซต์',value:data?String(data.totals.totalSections):'—',detail:'หน้าแรก บริการ ผลงาน และแบรนด์',icon:Layers,color:'purple'},{label:'โปรเจกต์ในแกลเลอรี',value:data?String(data.sections.projects.count):'—',detail:'โฟลเดอร์ผลงานบนเว็บไซต์',icon:FolderOpen,color:'amber'},{label:'อัปเดตเนื้อหาล่าสุด',value:data?.totals.lastModified?timeAgo(data.totals.lastModified):'—',detail:data?.totals.lastModified?new Date(data.totals.lastModified).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'ยังไม่มีวันที่อัปเดต',icon:Clock,color:'green'}].map(metric=><article key={metric.label} className={styles.metric} aria-busy={loading}><div><span className={`${styles.icon} ${styles[metric.color]}`}><metric.icon size={18}/></span><p>{metric.label}</p></div><strong className={loading?styles.loadingText:''}>{metric.value}</strong><span>{metric.detail}</span></article>)}
  </section>
  <div className={styles.contentGrid}><section className={styles.panel} aria-labelledby="content-heading"><div className={styles.panelHeading}><div><h2 id="content-heading">จัดการเนื้อหาเว็บไซต์</h2><p>เลือกส่วนที่ต้องการแก้ไข</p></div><span className={styles.counter}>05 SECTIONS</span></div><div className={styles.sectionList}>{sections.map(section=><Link key={section.key} href={`/${locale}/admin/${section.key}`} className={styles.sectionRow}><span className={`${styles.sectionIcon} ${styles[section.color]}`}><section.icon size={21}/></span><div className={styles.sectionName}><h3>{section.title}</h3><p>{section.description}</p></div><div className={styles.sectionInfo}><strong>{data?section.info(data):'—'}</strong><span>{data?timeAgo(data.sections[section.key].lastUpdated):'กำลังโหลด…'}</span></div><ChevronRight size={17} className={styles.rowArrow}/></Link>)}</div></section>
   <aside className={styles.rightColumn}><section className={styles.panel} aria-labelledby="shortcuts-heading"><div className={styles.panelHeading}><div><h2 id="shortcuts-heading">ทางลัดสำหรับทีม</h2><p>งานที่ใช้เป็นประจำ</p></div><Activity size={18}/></div><div className={styles.shortcuts}>{shortcuts.map(shortcut=><Link href={`/${locale}/admin/${shortcut.path}`} key={shortcut.path}><shortcut.icon size={19}/><div><h3>{shortcut.title}</h3><p>{shortcut.description}</p></div><ArrowUpRight size={15}/></Link>)}</div></section>
    <section className={styles.activity} aria-labelledby="activity-heading"><div className={styles.activityHeading}><h2 id="activity-heading">อัปเดตล่าสุด</h2><Clock size={16}/></div>{loading?<p className={styles.activityEmpty}>กำลังโหลดประวัติการอัปเดต…</p>:recent.length?recent.slice(0,3).map(section=><Link key={section.key} href={`/${locale}/admin/${section.key}`}><span className={`${styles.dot} ${styles[section.color]}`}/><div><strong>{section.title}</strong><span>{timeAgo(data!.sections[section.key].lastUpdated)}</span></div><ArrowUpRight size={14}/></Link>):<p className={styles.activityEmpty}>{error?'ยังโหลดวันที่อัปเดตไม่ได้':'ยังไม่มีวันที่อัปเดตที่บันทึกไว้'}</p>}</section>
   </aside></div>
 </div>;
}
